<a href="https://colab.research.google.com/github/RYOMAKUNG/KKU_data_mining/blob/master/Data103_Distance.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [51]:
import numpy as np

In [52]:
np1 = np.array([[1,3,5],[2,4,6]])
np1

array([[1, 3, 5],
       [2, 4, 6]])

In [53]:
np2 = np.array([[1,2],[3,5],[2,0],[4,5]])
np2

array([[1, 2],
       [3, 5],
       [2, 0],
       [4, 5]])

In [54]:
np2 [0,:]

array([1, 2])

##HW6 สร้างdistance metrix(mahattan and euclidean)ของnp2
##โดยสร้างfuncionสำหรับคำนวณmahattan distance and euclidean distance
def euclidean(data1,data2):
 ## #process
 return dist

In [55]:
import math

In [56]:
def Euclidean(data1,data2):
    distX = pow((data1[0]-data2[0]),2)
    distY = pow((data1[1]-data2[1]),2)
    return math.sqrt(distX+distY)

In [57]:
dist_math1 = np.zeros((4,4))
dist_math1

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [58]:
for i in range(4):
    for j in range(4):
        dist_math1[i,j] = Euclidean(np2[i,:],np2[j,:])
dist_math1

array([[0.        , 3.60555128, 2.23606798, 4.24264069],
       [3.60555128, 0.        , 5.09901951, 1.        ],
       [2.23606798, 5.09901951, 0.        , 5.38516481],
       [4.24264069, 1.        , 5.38516481, 0.        ]])

In [59]:
import math

In [60]:
def Manhattan(data1,data2):
  distX=data1[0]-data2[0]
  return distX

In [61]:
Manhattan(np2[0,:],np2[1,:])

-2

In [62]:
def Manhattan(data1,data2):
  distX=data1[0]-data2[0]
  distY=data1[1]-data2[1]
  return distX+distY

In [63]:
Manhattan(np2[0,:],np2[1,:])

-5

In [64]:
dist_mat=np.zeros((4,4))
dist_mat

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [65]:
for i in range(4):
  for j in range(4):
    dist_mat[i,j]= Manhattan(np2[i,:],np2[j,:])
dist_mat    

array([[ 0., -5.,  1., -6.],
       [ 5.,  0.,  6., -1.],
       [-1., -6.,  0., -7.],
       [ 6.,  1.,  7.,  0.]])

In [66]:
np2.shape

(4, 2)

##Distance of nominal or categorical features

In [67]:
d_a={'a':1,2:3,3:5,'cat':6}

In [68]:
d_a

{2: 3, 3: 5, 'a': 1, 'cat': 6}

In [69]:
d_a['cat']

6

In [70]:
d_a['dog']=[1,2,3]

In [71]:
d_a

{2: 3, 3: 5, 'a': 1, 'cat': 6, 'dog': [1, 2, 3]}

In [72]:
import pandas as pd

In [73]:
data_dict = {'color':['red','red','green'],'status':['single','married','single']}
data_dict

{'color': ['red', 'red', 'green'], 'status': ['single', 'married', 'single']}

In [74]:
data_pd = pd.DataFrame.from_dict(data_dict)
data_pd

color   status
0    red   single
1    red  married
2  green   single

##Categoricalnfeature distance method#1

In [75]:
list(data_pd.iloc[1,:])

['red', 'married']

In [76]:
def meth1_dist(data1,data2):
    N=0
    print (f' data1 is {data1} and data2 is {data2}')
    for i in range(len(data1)):
        print(f'feature1 of data1 is {data1[i]},feature1 os data2 is {data2[i]}')
        if data1[i] != data2[i]:
           N = N+1
           print(f'{data1[i]} is not equal {data2[i]} : update({N})')
        else:
            print(f' {data1[i]} is equal {data2[i]}')
    return N/len(data1)

In [77]:
meth1_dist(list(data_pd.iloc[0,:]),list(data_pd.iloc[1,:]))

 data1 is ['red', 'single'] and data2 is ['red', 'married']
feature1 of data1 is red,feature1 os data2 is red
 red is equal red
feature1 of data1 is single,feature1 os data2 is married
single is not equal married : update(1)


0.5

##HW7 calculate distance matrix of data_pd using meth1_dist()

#categorical feature distance method#2

In [78]:
pd.get_dummies(data_pd)

color_green  color_red  status_married  status_single
0            0          1               0              1
1            0          1               1              0
2            1          0               0              1

In [79]:
def binary_sym_dist(data1,data2):
  r=0
  q=0
  s=0
  t=0
  for i in range(len(data1)):
    if data1[i] != data2[i]:
      if data1[i]==1:
       q=q+1
      else:
        t=t+1
    if data1[i] != data2[i]:  
     rs=rs+1
  return (rs)/(q+rs+t)

In [80]:
binary_sym_dist(list(data_pd.iloc[0,:]),list(data_pd.iloc[1,:]))

UnboundLocalError: ignored