<a href="https://colab.research.google.com/github/RYOMAKUNG/KKU_data_mining/blob/master/Data103_Distance.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

In [4]:
np1 = np.array([[1,3,5],[2,4,6]])
np1

array([[1, 3, 5],
       [2, 4, 6]])

In [8]:
np2 = np.array([[1,2],[3,5],[2,0],[4,5]])
np2

array([[1, 2],
       [3, 5],
       [2, 0],
       [4, 5]])

In [15]:
np2 [0,:]

array([1, 2])

##HW6 สร้างdistance metrix(mahattan and euclidean)ของnp2
##โดยสร้างfuncionสำหรับคำนวณmahattan distance and euclidean distance
def euclidean(data1,data2):
 ## #process
 return dist

In [28]:
def Manhattan(data1,data2):
  distX=data1[0]-data2[0]
  return distX

In [29]:
Manhattan(np2[0,:],np2[1,:])

-2

In [35]:
def Manhattan(data1,data2):
  distX=data1[0]-data2[0]
  distY=data1[1]-data2[1]
  return distX+distY

In [36]:
Manhattan(np2[0,:],np2[1,:])

-5

In [33]:
dist_mat=np.zeros((4,4))
dist_mat

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [37]:
for i in range(4):
  for j in range(4):
    dist_mat[i,j]= Manhattan(np2[i,:],np2[j,:])
dist_mat    

array([[ 0., -5.,  1., -6.],
       [ 5.,  0.,  6., -1.],
       [-1., -6.,  0., -7.],
       [ 6.,  1.,  7.,  0.]])

In [38]:
np2.shape

(4, 2)